[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "layer-ai-sdk"
version = "0.1.0"
description = "AI Agent Permission SDK"
requires-python = ">=3.9"

dependencies = [
    "requests"
]

[tool.setuptools]
packages = ["sdk"]
